### ISSUE TITLE
Bounding box of blockMesh panel are not aligned

### ISSUE THREAD

**Issue by EstrangedNeurons** [FOSSEE/venturial#1]
While selecting blockMesh panel options mouse clicks are responsive only near the text of the panel category. Closer to the boundary the clicks are not responsive.

**Comment by rajdeepadak** [comment]
Thanks for the bug report. It seems to be an issue with operator bounding box. The blockmesh panel options are actually embossed operators surrounded by a box and distributed horizontally to create the effect of horizontal tabs. This was done as  Blender UI design tools are inadequate for horizontal tabs. A b

**Comment by rajdeepadak** [comment]
Thanks for the bug report. It seems to be an issue with operator bounding box. The blockmesh panel options are actually embossed operators surrounded by a box and distributed horizontally to create the effect of horizontal tabs. This was done as Blender UI design tools are inadequate for horizontal tabs. A bug fix should be released by EOD.

**Comment by rajdeepadak** [comment]
Bug fix added. Closing this issue. Reopen this issue if it requires further modifications.
