### ISSUE TITLE
Bug with New mesh button

### ISSUE THREAD

**Issue by ashuftw** [FOSSEE/venturial#6]
The contents of the new mesh button prompt are disabled after pressing the cancel button in the file browser opened previously via the New mesh button.

**Comment by rajdeepadak** [comment]
Added bug fix to this issue.
The new mesh prompt contains a button to open the file browser which in turn displays the new mesh prompt by default. Clicking the file browser button again running will result a recursive call to a modal operator. This caused a segmentation fault and the entire blender window closes abruptly. Hence it is required to disable the new mesh prompt while the file browser modal operator is still running. After cancelling the file browser, the new mesh prompt is re-enabled when pressed. This solved the issue.
